### ISSUE TITLE
pip install not working with newer cython

### ISSUE THREAD

**Issue by elhuhdron** [janelia-flyem/gala#44]
Upgrade to cython 0.22 and then install via pip.
First error says no *.pyx files found (line 59). Edited setup.py to change to *.py and then build continues and files with compile error in agglo.py

**Comment by elhuhdron** [comment]
Maybe the wrong reason. The features/*.pyx files are not downloading to the tmp dir for the pip install.

**Comment by jni** [comment]
Hi @elhuhdron. Thanks for reporting! It looks like the Cython .pyx files were not packaged in the pip source distribution for some reason. Sorry, first time distributing Cython code! I'm exploring the solution. In the meantime, if you want to get something working quickly, you can download the current master from here and build with `python setup.py install`.

**Comment by elhuhdron** [comment]
No problem. Thanks for making the project available!
Yup, I was able to workaround by running pip install, letting it fail, then copying the *.pyx files over from a local git clone, then re-running pip install (which for me doesn't re-download, just reruns setup from the tmp folder).

Although the README is quite good compared to other projects I've seen, I noticed a couple missing dependencies:
    > sudo pip install viridis
    > sudo pip install libtiff
Then I modified gala/imio.py libtiff import for possible name change for pylibtiff:
try:
    from pylibtiff import TIFF
except:
    try:
        from libtiff import TIFF
    except:
        print("pylibtiff not available: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pylibtiff")

Also, incase anyone else is still using Centos 6.5 and hasn't upgraded python, looks like python 2.6 will work fine except:
    > sudo pip install unittest2
and the known deep copy issue (use patch to fix copy.py): 
http://bugs.python.org/issue1515

**Comment by jni** [comment]
@elhuhdron Thanks for commenting on the README, too! =) See also the readthedocs site: https://gala.readthedocs.org. 

This issue should be fixed in 0.2.2, now available on PyPI. Can you confirm that it works? I'm closing this for now, but feel free to reopen if you encounter more issues.

To address your other comments:

- *additional dependencies*: Oops! There's various places where the requirements are listed and they fell through the cracks in the readme. I've added them.
- *pylibtiff import*: this is also fixed. I guess I haven't used it in a while.
- *2.6 support*: I'm glad you've got it working with some mods! Gala was originally developed on 2.6, so this isn't surprising. However, I'm not interested in maintaining such backwards compatibility. Gala is definitely future-looking and intended to be used with the full scientific Python stack, and often with dependencies on the latest library releases (e.g. scikit-learn 0.15). I recommend using conda to manage environments with more recent Python version without messing with your system Python install.

**Comment by elhuhdron** [comment]
Perfect. Tried on another machine that I hadn't installed on yet and it worked. The upgrade on the same machine also worked fine. Also the libtiff change works (or at least no warning printed). Thanks!

**Comment by jni** [comment]
Awesome! For usage questions, feel free to [post to the mailing list](http://gala.30861.n7.nabble.com)! =)
